#include "src/game/envfx_snow.h"

const GeoLayout rex_eye_control_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, -1, rex_head_mesh_layer_1_mat_override_eyes_open_v4_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout rex_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 45, 7, rex_body_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 22, 19, -6, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -15, 0, rex_foot_L_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -22, 19, -6, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -15, 0, rex_foot_R_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_SHADOW(1, 150, 100),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, rex_tail_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, -19, rex_tail_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, rex_upper_body_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 45, -4, rex_upper_body_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, -1, rex_head_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, rex_eye_control_opt1),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 19, 8, 4, rex_shoulder_L_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, rex_arm_L_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 14, 0, 0, rex_arm_L_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -19, 8, 4, rex_shoulder_R_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, rex_arm_R_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -14, 0, 0, rex_arm_R_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, 9, 9, -14, rex_wing_L_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_ALPHA, -9, 9, -14, rex_wing_R_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, rex_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, rex_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
